CREATE TABLE homepage_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_key TEXT NOT NULL UNIQUE,
    stat_value INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE homepage_stats IS 'Stores configurable statistics for the homepage, like number of countries and US states.';

-- Seed initial values based on current hardcoded values
INSERT INTO homepage_stats (stat_key, stat_value) VALUES
('countries_count', 11),
('us_states_count', 30); -- The '+' will be added by the frontend

-- Trigger to automatically update updated_at timestamp on row update
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER homepage_stats_updated_at_trigger
BEFORE UPDATE ON homepage_stats
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
